### ISSUE TITLE
Items Manual Entry Screen: Save categories to localStorage and also change checkbox colors

### ISSUE THREAD

**Issue by bsaikiran618** [coding-Studio-vbit/ReliefRiders#108]

**Comment by Revantark** [comment]
Categories are being saved to sessionStorage.
Checkbox colors when changed , they does not look like checkboxes.

**Comment by bsaikiran618** [comment]
> Categories are saved to sessionStorage now.
> Checkbox colors when changed , they does not look like checkboxes.

We added colors in the upload image screen, so we need to keep it consistent

**Comment by Revantark** [comment]
We need to remove there too.

**Comment by bsaikiran618** [comment]
nice
