### ISSUE TITLE
Refactor Backend code and separate endpoint logic into controllers

### ISSUE THREAD

**Issue by bsaikiran618** [coding-Studio-vbit/ReliefRiders#113]

**Comment by Saravanan-Jodavula** [comment]
@bsaikiran618 @shivanishivalenka how is this going?

**Comment by bsaikiran618** [comment]
Haven't started this yet myself. I will do this once I finish my current tasks in the project

**Comment by Saravanan-Jodavula** [comment]
Alright, but make sure that the backend PRs coming in follow the same convention in order to reduce re-work

**Comment by bsaikiran618** [comment]
done
