### ISSUE TITLE
Choose Request Type screen is not responsive

### ISSUE THREAD

**Issue by bsaikiran618** [coding-Studio-vbit/ReliefRiders#117]
![localhost_3000_home_requester_new_request(Galaxy Fold)](https://user-images.githubusercontent.com/47565414/123982803-f5857d00-d9e0-11eb-81e5-aa4b2c0ac9f9.png)
![localhost_3000_home_requester_new_request(Galaxy S5)](https://user-images.githubusercontent.com/47565414/123982810-f74f4080-d9e0-11eb-9e28-b7713ddd363f.png)

**Comment by chandrakiran343** [comment]
It may be because that the styles are not adjusted to the global components used here, will try to fix it.
