### ISSUE TITLE
Requester Register - Add a Year Of Birth

### ISSUE THREAD

**Issue by SidMalladi** [coding-Studio-vbit/ReliefRiders#154]
@Revantark @Prashanith @yasaswiraj 
Currently, you have to manually enter the year of birth, along with the dashes.

It seems inconvenient.

Somebody from the front-end team, please look into this.

**Comment by Revantark** [comment]
We dont need to enter any dashes. All you need to enter in year of birth field is just a valid year.
Like 2000.

**Comment by bsaikiran618** [comment]
>  @Revantark @Prashanith @yasaswiraj 
> Currently, you have to manually enter the year of birth, along with the dashes.
> 
> It seems inconvenient.
> 
> Somebody from the front-end team, please look into this.
> 

Wait are you able to enter a date Into it like that?
